DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS transaction_types;
DROP TABLE IF EXISTS transaction_statuses;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS card_types;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS account_type;
DROP TABLE IF EXISTS account_status;